### ISSUE TITLE
Support TCP (and UDP?) in proxy rules

### ISSUE THREAD

**Issue by elevran** [amalgam8/sidecar#4]
Enable TCP / UDP proxy support in controller rules and sidecar

**Comment by rshriram** [comment]
unfortunately, openresty does not support balance_by_lua for TCP streams yet. Need to find third party modules that handle the scenario in a similar fashion.

**Comment by rshriram** [comment]
Submitted PR for balancer_by_lua support in nginx stream blocks. https://github.com/openresty/stream-lua-nginx-module/pull/30
