### ISSUE TITLE
Fetch service instances directly from registry

### ISSUE THREAD

**Issue by rshriram** [amalgam8/sidecar#42]
Currently sidecar relies on controller to provide a unified list of service instances and routing rules. Not only is this clumsy (registration to one entity, but discovery from another), it results in complicated data synchronization between registry and controller.

The sidecar should directly fetch instance information from registry and the rules information from the controller. Merging of instance info and rules should be done at the sidecar, followed by updating nginx routing tables.

In addition, the sidecar should cache both the instance and rules information in the event that the registry/controller become unavailable temporarily. Data should not be cached permanently.

**Comment by ijsnellf** [comment]
With the merge of https://github.com/amalgam8/controller/issues/51 and https://github.com/amalgam8/sidecar/issues/47 this issue should be resolved.
